# PlatformIO pre-build hook: gzip web/index.html into src/generated/web_index.h
# so the dashboard is edited as a normal HTML file but served from flash.
import gzip
import os

Import("env")  # noqa: F821 — provided by PlatformIO/SCons

root = env.subst("$PROJECT_DIR")
src = os.path.join(root, "web", "index.html")
out_dir = os.path.join(root, "src", "generated")
out = os.path.join(out_dir, "web_index.h")

if not os.path.exists(out) or os.path.getmtime(src) > os.path.getmtime(out):
    with open(src, "rb") as f:
        data = gzip.compress(f.read(), compresslevel=9, mtime=0)
    rows = [", ".join("0x%02x" % b for b in data[i : i + 16]) for i in range(0, len(data), 16)]
    os.makedirs(out_dir, exist_ok=True)
    with open(out, "w") as f:
        f.write("// Generated by scripts/embed_web.py from web/index.html — do not edit\n")
        f.write("#pragma once\n#include <stddef.h>\n#include <stdint.h>\n\n")
        f.write("static const uint8_t WEB_INDEX_GZ[] = {\n    " + ",\n    ".join(rows) + "};\n")
        f.write("static const size_t WEB_INDEX_GZ_LEN = sizeof(WEB_INDEX_GZ);\n")
    print("embed_web: web/index.html -> %d bytes gzipped" % len(data))
