# PlatformIO pre-build hook: writes `git describe` into src/generated/version.h
# so the firmware and the dashboard can report which build is running.
# Rewritten only when the value changes, so an ordinary commit does not force a
# full rebuild.
from __future__ import annotations

import os
import subprocess

Import("env")  # noqa: F821 -- provided by PlatformIO/SCons

root: str = env.subst("$PROJECT_DIR")
version: str
try:
    version = subprocess.check_output(
        ["git", "describe", "--tags", "--always", "--dirty"],
        cwd=root, text=True, stderr=subprocess.DEVNULL,
    ).strip()
except (OSError, subprocess.CalledProcessError):
    version = "unknown"

out: str = os.path.join(root, "src", "generated", "version.h")
text: str = (
    "// Generated by scripts/version.py -- do not edit\n"
    "#pragma once\n"
    '#define FW_VERSION "%s"\n' % version
)
if not os.path.exists(out) or open(out).read() != text:
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write(text)
    print("version: " + version)
